
package View;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

public class Index extends javax.swing.JFrame {


    public Index() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        clientes = new javax.swing.JMenuItem();
        proveedores = new javax.swing.JMenuItem();
        fabricantes = new javax.swing.JMenuItem();
        bibicletas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        motocicletas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        compras = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu.png"))); // NOI18N
        jMenu1.setText("Menú");

        jMenuItem1.setText("Ayuda");
        jMenu1.add(jMenuItem1);

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/man.png"))); // NOI18N
        jMenu3.setText("Usuarios");

        clientes.setText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        jMenu3.add(clientes);

        proveedores.setText("Proveedores");
        proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresActionPerformed(evt);
            }
        });
        jMenu3.add(proveedores);

        fabricantes.setText("Fabricantes");
        fabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fabricantesActionPerformed(evt);
            }
        });
        jMenu3.add(fabricantes);

        jMenuBar1.add(jMenu3);

        bibicletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/bicicleta.png"))); // NOI18N
        bibicletas.setText("Bicicletas");

        jMenuItem2.setText("Bicicletas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        bibicletas.add(jMenuItem2);

        jMenuBar1.add(bibicletas);

        motocicletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/moto.png"))); // NOI18N
        motocicletas.setText("Motocicletas");

        jMenuItem3.setText("Motocicletas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        motocicletas.add(jMenuItem3);

        jMenuBar1.add(motocicletas);

        compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/verificar.png"))); // NOI18N
        compras.setText("Compras");

        jMenuItem4.setText("Compras");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        compras.add(jMenuItem4);

        jMenuBar1.add(compras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        Clientes vc = new Clientes();
        centerWindow(vc);
    }//GEN-LAST:event_clientesActionPerformed

    private void proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresActionPerformed
        Proveedores pc = new Proveedores();
        centerWindow(pc);
    }//GEN-LAST:event_proveedoresActionPerformed

    private void fabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fabricantesActionPerformed
        Fabricantes fc = new Fabricantes();
        centerWindow(fc);
    }//GEN-LAST:event_fabricantesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Bicicletas bc = new Bicicletas();
        centerWindow(bc);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Motocicletas mc = new Motocicletas();
        centerWindow(mc);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Compras cc = new Compras();
        centerWindow(cc);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void centerWindow(JInternalFrame frame){
        panelPrincipal.add(frame);
        Dimension dm = panelPrincipal.getSize();
        Dimension dmv = frame.getSize();
        frame.setLocation((dm.width - dmv.height )/2, (dm.height - dmv.width)/2);
        frame.show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bibicletas;
    private javax.swing.JMenuItem clientes;
    private javax.swing.JMenu compras;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem fabricantes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu motocicletas;
    private javax.swing.JDesktopPane panelPrincipal;
    private javax.swing.JMenuItem proveedores;
    // End of variables declaration//GEN-END:variables
}
